name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        perl: [ "5.42", "5.40" ]
        distribution: [ strawberry, default ]
        exclude:
          - os: macos-latest
            distribution: strawberry
          - os: ubuntu-latest
            distribution: strawberry

    steps:
      - uses: actions/checkout@v6
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@main
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ matrix.distribution }}
      - name: Install Perl Module Manager
        run: cpm install -g Carmel@v0.1.56  # x:cpanm

      - name: Install Perl Module Dependencies for Windows
        if: runner.os == 'Windows'
        run: |
          carmel install
        env:
          OPENSSL_PREFIX: C:\Progra~1\OpenSSL

      - name: Install Perl Module Dependencies
        if: runner.os != 'Windows'
        run: carmel install

      - run: |
          carmel exec perl Build.PL
          carmel exec perl Build build
          carmel exec perl Build test
