name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        perl: [ "5.42", "5.40" ]
        include:
          - os: windows-latest
            distribution: strawberry
          - os: macos-latest
            distribution: default
          - os: ubuntu-latest
            distribution: default

    steps:
      - uses: actions/checkout@v6
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@main
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ matrix.distribution }}
      - name: cc --version
        if: runner.os == 'Windows'
        run: |
          perl -V:cc -V:ccversion -V:make
          gcc --version
#       cc -V:cc -V:ccversion -V:make

      - name: Install Perl Module Manager
        run: cpm install -g Carmel@v0.1.56  # x:cpanm

      - name: Install Perl Module Dependencies for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          carmel install
        env:
          OPENSSL_PREFIX: C:\Program Files\OpenSSL-Win64

      - name: Install Perl Module Dependencies
        if: runner.os != 'Windows'
        run: |
          carmel install

      - run: |
          carmel exec perl Build.PL
          carmel exec perl Build build
          carmel exec perl Build test
